### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Gavin-Attard-120feet/CryptoMe#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) Please provide blank input validation for the parameters "Event" and "To Encrypt" without which we are seeing error "Error in makeTableMap. Required argument tableObj not supplied".
2) The documentation url [https://www.120feet.com/?p=652&preview=true](https://www.120feet.com/?p=652&preview=true) provided is not valid. It is showing "404 page not found" error.

**Comment by Gavin-Attard-120feet** [comment]
Hi Pravevena and thank you, 

on 1. the template has been updated accordingly as has the metatdata sha ref. 
on 2. We have removed the documentation ref for the time being and will update it once published.
